name: Update UK Postcodes

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Run postcode update script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python backend/update_data.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Deepak-Sekar-p/hello-grad.git
          
          # Stash any unstaged changes to avoid conflicts
          git stash push -m "Temporary changes"

          # Pull the latest changes to avoid conflicts
          git pull origin main --rebase || git pull --rebase --allow-unrelated-histories

          # Apply any stashed changes back
          git stash pop || echo "No stashed changes to apply"

          # Ensure the data directory exists
          mkdir -p data

          # Check if data file exists before committing
          if [ -f "data/uk_postcodes.json" ]; then
            git add data/uk_postcodes.json
            git commit -m "Auto-update postcode data" || echo "No changes to commit"
            git push origin main
          else
            echo "No data file found, skipping commit step."
          fi
