name: Update UK Postcodes

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default credentials to use PAT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Debug API Key
        env:
          ORDNANCE_SURVEY_API_KEY: ${{ secrets.ORDNANCE_SURVEY_API_KEY }}
        run: echo "API Key starts with ${ORDNANCE_SURVEY_API_KEY:0:5}"

      - name: Run postcode update script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          ORDNANCE_SURVEY_API_KEY: ${{ secrets.ORDNANCE_SURVEY_API_KEY }}
        run: python backend/update_data.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Deepak-Sekar-p/hello-grad.git

          # Ensure the data directory exists
          mkdir -p data

          # Check if data file exists before committing
          if [ -f "data/uk_postcodes.json" ]; then
            git add data/uk_postcodes.json
            git commit -m "Auto-update postcode data" || echo "No changes to commit"
            git push origin main
          else
            echo "No data file found, skipping commit step."
          fi
